"""add_materials_to_orders

Revision ID: 172fb6762889
Revises: dd8da7ff12dc
Create Date: 2026-03-23 09:13:10.674446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172fb6762889'
down_revision: Union[str, None] = 'dd8da7ff12dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('materials', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'materials')
    # ### end Alembic commands ###
