"""add_taken_at_and_notify_assignments

Revision ID: 52cf2f011278
Revises: 905352ce8995
Create Date: 2026-03-06 23:32:28.470810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cf2f011278'
down_revision: Union[str, None] = '905352ce8995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_assignments', sa.Column('taken_at', sa.DateTime(), nullable=True))
    op.add_column('team_members', sa.Column('notify_assignments', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'notify_assignments')
    op.drop_column('order_assignments', 'taken_at')
    # ### end Alembic commands ###
