"""add_group_message_id_to_assignments

Revision ID: 6a78c2818f95
Revises: 52cf2f011278
Create Date: 2026-03-08 12:52:55.166810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a78c2818f95'
down_revision: Union[str, None] = '52cf2f011278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_assignments', sa.Column('group_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_assignments', 'group_message_id')
    # ### end Alembic commands ###
