"""add_response_price_to_orders

Revision ID: 905352ce8995
Revises: c6e3d4aecbc7
Create Date: 2026-03-05 12:06:37.994332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905352ce8995'
down_revision: Union[str, None] = 'c6e3d4aecbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('response_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'response_price')
    # ### end Alembic commands ###
