"""v2_add_new_fields_and_enum_values

Revision ID: c6e3d4aecbc7
Revises: 08a2e3a77ee7
Create Date: 2026-03-05 07:44:07.620341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e3d4aecbc7'
down_revision: Union[str, None] = '08a2e3a77ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем новые значения в enum AssignmentStatus (до изменения колонок)
    op.execute("ALTER TYPE assignmentstatus ADD VALUE IF NOT EXISTS 'rejected'")
    op.execute("ALTER TYPE assignmentstatus ADD VALUE IF NOT EXISTS 'reassigned'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager_responses', sa.Column('edited_text', sa.Text(), nullable=True))
    op.add_column('manager_responses', sa.Column(
        'sent_to_client', sa.Boolean(), nullable=False, server_default=sa.text('false'),
    ))
    op.add_column('manager_responses', sa.Column('sent_to_client_at', sa.DateTime(), nullable=True))
    op.add_column('order_assignments', sa.Column('roadmap_text', sa.Text(), nullable=True))
    op.add_column('order_assignments', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.add_column('order_assignments', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_order_assignments_assigned_by_team_members',
        'order_assignments', 'team_members', ['assigned_by'], ['id'],
    )
    op.add_column('team_members', sa.Column(
        'tech_stack', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json"),
    ))
    op.add_column('team_members', sa.Column(
        'stack_priority', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json"),
    ))
    op.add_column('team_members', sa.Column(
        'bio', sa.Text(), nullable=False, server_default=sa.text("''"),
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'bio')
    op.drop_column('team_members', 'stack_priority')
    op.drop_column('team_members', 'tech_stack')
    op.drop_constraint(
        'fk_order_assignments_assigned_by_team_members', 'order_assignments', type_='foreignkey',
    )
    op.drop_column('order_assignments', 'rejection_reason')
    op.drop_column('order_assignments', 'assigned_by')
    op.drop_column('order_assignments', 'roadmap_text')
    op.drop_column('manager_responses', 'sent_to_client_at')
    op.drop_column('manager_responses', 'sent_to_client')
    op.drop_column('manager_responses', 'edited_text')
    # ### end Alembic commands ###
